# Generated by Django 2.2 on 2020-03-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200223_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
