# Generated by Django 2.2 on 2020-01-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20200108_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
